GRANT USAGE ON SCHEMA incidents TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA incidents TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA incidents TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA incidents TO "apps";