GRANT USAGE ON SCHEMA presences_statistics TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA presences_statistics TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA presences_statistics TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA presences_statistics TO "apps";