export enum EventType {
    ABSENCE = 1,
    LATENESS = 2,
    DEPARTURE = 3,
    REMARK = 4,
    INCIDENT
}

export enum EVENT_TYPES {
    UNJUSTIFIED = "UNJUSTIFIED",
    JUSTIFIED = "JUSTIFIED",
    LATENESS = "LATENESS",
    DEPARTURE = "DEPARTURE",
    INCIDENT = "INCIDENT",
    PUNISHMENT = "PUNISHMENT",
    SANCTION = "SANCTION",
    NOTEBOOK = "NOTEBOOK"
}