GRANT USAGE ON SCHEMA presences TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA presences TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA presences TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA presences TO "apps";