export * from './incidentsTypeManage'
export * from './incidentsPlaceManage'
export * from './incidentsProtagonistsManage'
export * from './incidentsSeriousnessManage'
export * from './incidentsPartnersManage'