export enum FILTER_TYPE {
    UNJUSTIFIED_ABSENCE = "UNJUSTIFIED_ABSENCE",
    JUSTIFIED_UNREGULARIZED_ABSENCE = "JUSTIFIED_UNREGULARIZED_ABSENCE",
    REGULARIZED_ABSENCE = "REGULARIZED_ABSENCE",
    LATENESS = "LATENESS",
    INCIDENT = "INCIDENT",
    PUNISHMENT = "PUNISHMENT",
    SANCTION = "SANCTION",
    DEPARTURE = "DEPARTURE"
}