export enum FILTER_TYPE {
    NO_REASON = "NO_REASON",
    UNREGULARIZED = "UNREGULARIZED",
    REGULARIZED = "REGULARIZED",
    LATENESS = "LATENESS",
    INCIDENT = "INCIDENT",
    PUNISHMENT = "PUNISHMENT",
    SANCTION = "SANCTION",
    DEPARTURE = "DEPARTURE",
    // ABSENCE TOTAL added in order to manipulate its string for rate/count
    ABSENCE_TOTAL = "ABSENCE_TOTAL",
}