export enum FILTER_TYPE {
    NO_REASON = "NO_REASON",
    UNREGULARIZED = "UNREGULARIZED",
    REGULARIZED = "REGULARIZED",
    LATENESS = "LATENESS",
    INCIDENT = "INCIDENT",
    PUNISHMENT = "PUNISHMENT",
    SANCTION = "SANCTION",
    DEPARTURE = "DEPARTURE"
}