GRANT USAGE ON SCHEMA massmailing TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA massmailing TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA massmailing TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA massmailing TO "apps";