name: dev-check-repository

on: [push]

jobs:
  build-node-test:
    runs-on: ubuntu-latest

    container:
      image: opendigitaleducation/node:22-alpine-pnpm
      options: --user root -v ${{ github.workspace }}:/home/node/:rw

    steps:
      - uses: actions/checkout@v1
      - name: Run pnpm install
        run: pnpm install
      - name: Run build with Vite
        run: pnpm run build:presences && pnpm run build:incidents && pnpm run build:statistics-presences && pnpm run build:massmailing
      - name: Run test
        run: pnpm test

  build-maven-test:
    runs-on: ubuntu-latest

    container:
      image: maven:3.8.6-jdk-8
      options: --user root -v ${{ github.workspace }}:/home/maven/:rw

    steps:
      - uses: actions/checkout@v1
      - name: Run build maven
        run: mvn -Duser.home=/var/maven clean install
      - name: Run maven test
        run: mvn -Duser.home=/var/maven test
